export const states = [
  {
    title: "State",
    values: [
      "Andhra Pradesh",
      "Arunachal Pradesh",
      "Assam",
      "Bihar",
      "Chhattisgarh",
      "Goa",
      "Gujarat",
      "Haryana",
      "Himachal Pradesh",
      "Jammu and Kashmir",
      "Jharkhand",
      "Karnataka",
      "Kerala",
      "Madhya Pradesh",
      "Maharashtra",
      "Manipur",
      "Meghalaya",
      "Mizoram",
      "Nagaland",
      "Odisha",
      "Punjab",
      "Rajasthan",
      "Sikkim",
      "Tamil Nadu",
      "Telangana",
      "Tripura",
      "Uttarakhand",
      "Uttar Pradesh",
      "West Bengal",
    ],
  },
  {
    title: "Union Territory",
    values: [
      "Andaman and Nicobar Islands",
      "Chandigarh",
      "Dadra and Nagar Haveli",
      "Daman and Diu",
      "Delhi",
      "Lakshadweep",
      "Puducherry",
    ],
  },
];

export const countryList = [
  {
    title: "A",
    values: [
      "Afghanistan",
      "Albania",
      "Algeria",
      "Andorra",
      "Angola",
      "Anguilla",
      "Antigua & Barbuda",
      "Argentina",
      "Armenia",
      "Aruba",
      "Australia",
      "Austria",
      "Azerbaijan",
    ],
  },
  {
    title: "B",
    values: [
      "Bahamas",
      "Bahrain",
      "Bangladesh",
      "Barbados",
      "Belarus",
      "Belgium",
      "Belize",
      "Benin",
      "Bermuda",
      "Bhutan",
      "Bolivia",
      "Bosnia & Herzegovina",
      "Botswana",
      "Brazil",
      "British Virgin Islands",
      "Brunei",
      "Bulgaria",
      "Burkina Faso",
      "Burundi",
    ],
  },
  {
    title: "C",
    values: [
      "Cambodia",
      "Cameroon",
      "Canada",
      "Cape Verde",
      "Cayman Islands",
      "Chad",
      "Chile",
      "China",
      "Colombia",
      "Congo",
      "Cook Islands",
      "Costa Rica",
      "Cote D Ivoire",
      "Croatia",
      "Cruise Ship",
      "Cuba",
      "Cyprus",
      "Czech Republic",
    ],
  },
  {
    title: "D",
    values: ["Denmark", "Djibouti", "Dominica", "Dominican Republic"],
  },
  {
    title: "E",
    values: [
      "Ecuador",
      "Egypt",
      "El Salvador",
      "Equatorial Guinea",
      "Estonia",
      "Ethiopia",
    ],
  },
  {
    title: "F",
    values: [
      "Falkland Islands",
      "Faroe Islands",
      "Fiji",
      "Finland",
      "France",
      "French Polynesia",
      "French West Indies",
    ],
  },
  {
    title: "G",
    values: [
      "Gabon",
      "Gambia",
      "Georgia",
      "Germany",
      "Ghana",
      "Gibraltar",
      "Greece",
      "Greenland",
      "Grenada",
      "Guam",
      "Guatemala",
      "Guernsey",
      "Guinea",
      "Guinea Bissau",
      "Guyana",
    ],
  },
  {
    title: "H",
    values: ["Haiti", "Honduras", "Hong Kong", "Hungary"],
  },
  {
    title: "I",
    values: [
      "Iceland",
      "India",
      "Indonesia",
      "Iran",
      "Iraq",
      "Ireland",
      "Isle of Man",
      "Israel",
      "Italy",
    ],
  },
  {
    title: "J",
    values: ["Jamaica", "Japan", "Jersey", "Jordan"],
  },
  {
    title: "K",
    values: ["Kazakhstan", "Kenya", "Kuwait", "Kyrgyz Republic"],
  },
  {
    title: "L",
    values: [
      "Laos",
      "Latvia",
      "Lebanon",
      "Lesotho",
      "Liberia",
      "Libya",
      "Liechtenstein",
      "Lithuania",
      "Luxembourg",
    ],
  },
  {
    title: "M",
    values: [
      "Macau",
      "Macedonia",
      "Madagascar",
      "Malawi",
      "Malaysia",
      "Maldives",
      "Mali",
      "Malta",
      "Mauritania",
      "Mauritius",
      "Mexico",
      "Moldova",
      "Monaco",
      "Mongolia",
      "Montenegro",
      "Montserrat",
      "Morocco",
      "Mozambique",
    ],
  },
  {
    title: "N",
    values: [
      "Namibia",
      "Nepal",
      "Netherlands",
      "Netherlands Antilles",
      "New Caledonia",
      "New Zealand",
      "Nicaragua",
      "Niger",
      "Nigeria",
      "Norway",
    ],
  },
  {
    title: "O",
    values: ["Oman"],
  },
  {
    title: "P",
    values: [
      "Pakistan",
      "Palestine",
      "Panama",
      "Papua New Guinea",
      "Paraguay",
      "Peru",
      "Philippines",
      "Poland",
      "Portugal",
      "Puerto Rico",
    ],
  },
  {
    title: "Q",
    values: ["Qatar"],
  },
  {
    title: "R",
    values: ["Reunion", "Romania", "Russia", "Rwanda"],
  },
  {
    title: "S",
    values: [
      "Saint Pierre &amp; Miquelon",
      "Samoa",
      "San Marino",
      "Satellite",
      "Saudi Arabia",
      "Senegal",
      "Serbia",
      "Seychelles",
      "Sierra Leone",
      "Singapore",
      "Slovakia",
      "Slovenia",
      "South Africa",
      "South Korea",
      "Spain",
      "Sri Lanka",
      "St Kitts &amp; Nevis",
      "St Lucia",
      "St Vincent",
      "St. Lucia",
      "Sudan",
      "Suriname",
      "Swaziland",
      "Sweden",
      "Switzerland",
      "Syria",
    ],
  },
  {
    title: "T",
    values: [
      "Taiwan",
      "Tajikistan",
      "Tanzania",
      "Thailand",
      "Timor L'Este",
      "Togo",
      "Tonga",
      "Trinidad & Tobago",
      "Tunisia",
      "Turkey",
      "Turkmenistan",
      "Turks &amp; Caicos",
    ],
  },
  {
    title: "U",
    values: [
      "Uganda",
      "Ukraine",
      "United Arab Emirates",
      "United Kingdom",
      "Uruguay",
      "Uzbekistan",
    ],
  },
  {
    title: "V",
    values: ["Venezuela", "Vietnam", "Virgin Islands (US)"],
  },
  {
    title: "Y",
    values: ["Yemen"],
  },
  {
    title: "Z",
    values: ["Zambia", "Zimbabwe"],
  },
];

export const cities = [
  {
    title: "Andhra Pradesh",
    values: [
      "Adilabad",
      "Anantapur",
      "Chittoor",
      "Kakinada",
      "Guntur",
      "Hyderabad",
      "Karimnagar",
      "Khammam",
      "Krishna",
      "Kurnool",
      "Mahbubnagar",
      "Medak",
      "Nalgonda",
      "Nizamabad",
      "Ongole",
      "Hyderabad",
      "Srikakulam",
      "Nellore",
      "Visakhapatnam",
      "Vizianagaram",
      "Warangal",
      "Eluru",
      "Kadapa",
    ],
  },
  {
    title: "Arunachal Pradesh",
    values: [
      "Anjaw",
      "Changlang",
      "East Siang",
      "Kurung Kumey",
      "Lohit",
      "Lower Dibang Valley",
      "Lower Subansiri",
      "Papum Pare",
      "Tawang",
      "Tirap",
      "Dibang Valley",
      "Upper Siang",
      "Upper Subansiri",
      "West Kameng",
      "West Siang",
    ],
  },
  {
    title: "Assam",
    values: [
      "Baksa",
      "Barpeta",
      "Bongaigaon",
      "Cachar",
      "Chirang",
      "Darrang",
      "Dhemaji",
      "Dima Hasao",
      "Dhubri",
      "Dibrugarh",
      "Goalpara",
      "Golaghat",
      "Hailakandi",
      "Jorhat",
      "Kamrup",
      "Kamrup Metropolitan",
      "Karbi Anglong",
      "Karimganj",
      "Kokrajhar",
      "Lakhimpur",
      "Marigaon",
      "Nagaon",
      "Nalbari",
      "Sibsagar",
      "Sonitpur",
      "Tinsukia",
      "Udalguri",
    ],
  },
  {
    title: "Bihar",
    values: [
      "Araria",
      "Arwal",
      "Aurangabad",
      "Banka",
      "Begusarai",
      "Bhagalpur",
      "Bhojpur",
      "Buxar",
      "Darbhanga",
      "East Champaran",
      "Gaya",
      "Gopalganj",
      "Jamui",
      "Jehanabad",
      "Kaimur",
      "Katihar",
      "Khagaria",
      "Kishanganj",
      "Lakhisarai",
      "Madhepura",
      "Madhubani",
      "Munger",
      "Muzaffarpur",
      "Nalanda",
      "Nawada",
      "Patna",
      "Purnia",
      "Rohtas",
      "Saharsa",
      "Samastipur",
      "Saran",
      "Sheikhpura",
      "Sheohar",
      "Sitamarhi",
      "Siwan",
      "Supaul",
      "Vaishali",
      "West Champaran",
      "Chandigarh",
    ],
  },
  {
    title: "Chhattisgarh",
    values: [
      "Bastar",
      "Bijapur",
      "Bilaspur",
      "Dantewada",
      "Dhamtari",
      "Durg",
      "Jashpur",
      "Janjgir-Champa",
      "Korba",
      "Koriya",
      "Kanker",
      "Kabirdham (Kawardha)",
      "Mahasamund",
      "Narayanpur",
      "Raigarh",
      "Rajnandgaon",
      "Raipur",
      "Surguja",
    ],
  },
  {
    title: "Dadra and Nagar Haveli",
    values: ["Dadra and Nagar Haveli"],
  },
  {
    title: "Daman and Diu",
    values: ["Daman", "Diu"],
  },
  {
    title: "Delhi",
    values: [
      "Central Delhi",
      "East Delhi",
      "New Delhi",
      "North Delhi",
      "North East Delhi",
      "North West Delhi",
      "South Delhi",
      "South West Delhi",
      "West Delhi",
    ],
  },
  {
    title: "Goa",
    values: ["North Goa", "South Goa"],
  },
  {
    title: "Gujarat",
    values: [
      "Ahmedabad",
      "Amreli district",
      "Anand",
      "Banaskantha",
      "Bharuch",
      "Bhavnagar",
      "Dahod",
      "The Dangs",
      "Gandhinagar",
      "Jamnagar",
      "Junagadh",
      "Kutch",
      "Kheda",
      "Mehsana",
      "Narmada",
      "Navsari",
      "Patan",
      "Panchmahal",
      "Porbandar",
      "Rajkot",
      "Sabarkantha",
      "Surendranagar",
      "Surat",
      "Vyara",
      "Vadodara",
      "Valsad",
    ],
  },
  {
    title: "Haryana",
    values: [
      "Ambala",
      "Bhiwani",
      "Faridabad",
      "Fatehabad",
      "Gurgaon",
      "Hissar",
      "Jhajjar",
      "Jind",
      "Karnal",
      "Kaithal",
      "Kurukshetra",
      "Mahendragarh",
      "Mewat",
      "Palwal",
      "Panchkula",
      "Panipat",
      "Rewari",
      "Rohtak",
      "Sirsa",
      "Sonipat",
      "Yamuna Nagar",
    ],
  },
  {
    title: "Himachal Pradesh",
    values: [
      "Bilaspur",
      "Chamba",
      "Hamirpur",
      "Kangra",
      "Kinnaur",
      "Kullu",
      "Lahaul and Spiti",
      "Mandi",
      "Shimla",
      "Sirmaur",
      "Solan",
      "Una",
    ],
  },
  {
    title: "Jammu and Kashmir",
    values: [
      "Anantnag",
      "Badgam",
      "Bandipora",
      "Baramulla",
      "Doda",
      "Ganderbal",
      "Jammu",
      "Kargil",
      "Kathua",
      "Kishtwar",
      "Kupwara",
      "Kulgam",
      "Leh",
      "Poonch",
      "Pulwama",
      "Rajauri",
      "Ramban",
      "Reasi",
      "Samba",
      "Shopian",
      "Srinagar",
      "Udhampur",
    ],
  },
  {
    title: "Jharkhand",
    values: [
      "Bokaro",
      "Chatra",
      "Deoghar",
      "Dhanbad",
      "Dumka",
      "East Singhbhum",
      "Garhwa",
      "Giridih",
      "Godda",
      "Gumla",
      "Hazaribag",
      "Jamtara",
      "Khunti",
      "Koderma",
      "Latehar",
      "Lohardaga",
      "Pakur",
      "Palamu",
      "Ramgarh",
      "Ranchi",
      "Sahibganj",
      "Seraikela Kharsawan",
      "Simdega",
      "West Singhbhum",
    ],
  },
  {
    title: "Karnataka",
    values: [
      "Bagalkot",
      "Bangalore Rural",
      "Bangalore Urban",
      "Belgaum",
      "Bellary",
      "Bidar",
      "Bijapur",
      "Chamarajnagar",
      "Chikkamagaluru",
      "Chikkaballapur",
      "Chitradurga",
      "Davanagere",
      "Dharwad",
      "Dakshina Kannada",
      "Gadag",
      "Gulbarga",
      "Hassan",
      "Haveri district",
      "Kodagu",
      "Kolar",
      "Koppal",
      "Mandya",
      "Mysore",
      "Raichur",
      "Shimoga",
      "Tumkur",
      "Udupi",
      "Uttara Kannada",
      "Ramanagara",
      "Yadgir",
    ],
  },
  {
    title: "Kerala",
    values: [
      "Alappuzha",
      "Ernakulam",
      "Idukki",
      "Kannur",
      "Kasaragod",
      "Kollam",
      "Kottayam",
      "Kozhikode",
      "Malappuram",
      "Palakkad",
      "Pathanamthitta",
      "Thrissur",
      "Thiruvananthapuram",
      "Wayanad",
    ],
  },
  {
    title: "Madhya Pradesh",
    values: [
      "Alirajpur",
      "Anuppur",
      "Ashok Nagar",
      "Balaghat",
      "Barwani",
      "Betul",
      "Bhind",
      "Bhopal",
      "Burhanpur",
      "Chhatarpur",
      "Chhindwara",
      "Damoh",
      "Datia",
      "Dewas",
      "Dhar",
      "Dindori",
      "Guna",
      "Gwalior",
      "Harda",
      "Hoshangabad",
      "Indore",
      "Jabalpur",
      "Jhabua",
      "Katni",
      "Khandwa (East Nimar)",
      "Khargone (West Nimar)",
      "Mandla",
      "Mandsaur",
      "Morena",
      "Narsinghpur",
      "Neemuch",
      "Panna",
      "Rewa",
      "Rajgarh",
      "Ratlam",
      "Raisen",
      "Sagar",
      "Satna",
      "Sehore",
      "Seoni",
      "Shahdol",
      "Shajapur",
      "Sheopur",
      "Shivpuri",
      "Sidhi",
      "Singrauli",
      "Tikamgarh",
      "Ujjain",
      "Umaria",
      "Vidisha",
    ],
  },
  {
    title: "Maharashtra",
    values: [
      "Ahmednagar",
      "Akola",
      "Amravati",
      "Aurangabad",
      "Bhandara",
      "Beed",
      "Buldhana",
      "Chandrapur",
      "Dhule",
      "Gadchiroli",
      "Gondia",
      "Hingoli",
      "Jalgaon",
      "Jalna",
      "Kolhapur",
      "Latur",
      "Mumbai City",
      "Mumbai suburban",
      "Nandurbar",
      "Nanded",
      "Nagpur",
      "Nashik",
      "Osmanabad",
      "Parbhani",
      "Pune",
      "Raigad",
      "Ratnagiri",
      "Sindhudurg",
      "Sangli",
      "Solapur",
      "Satara",
      "Thane",
      "Wardha",
      "Washim",
      "Yavatmal",
    ],
  },
  {
    title: "Manipur",
    values: [
      "Bishnupur",
      "Churachandpur",
      "Chandel",
      "Imphal East",
      "Senapati",
      "Tamenglong",
      "Thoubal",
      "Ukhrul",
      "Imphal West",
    ],
  },
  {
    title: "Meghalaya",
    values: [
      "East Garo Hills",
      "East Khasi Hills",
      "Jaintia Hills",
      "Ri Bhoi",
      "South Garo Hills",
      "West Garo Hills",
      "West Khasi Hills",
    ],
  },
  {
    title: "Mizoram",
    values: [
      "Aizawl",
      "Champhai",
      "Kolasib",
      "Lawngtlai",
      "Lunglei",
      "Mamit",
      "Saiha",
      "Serchhip",
    ],
  },
  {
    title: "Nagaland",
    values: [
      "Dimapur",
      "Kohima",
      "Mokokchung",
      "Mon",
      "Phek",
      "Tuensang",
      "Wokha",
      "Zunheboto",
    ],
  },
  {
    title: "Orissa",
    values: [
      "Angul",
      "Boudh (Bauda)",
      "Bhadrak",
      "Balangir",
      "Bargarh (Baragarh)",
      "Balasore",
      "Cuttack",
      "Debagarh (Deogarh)",
      "Dhenkanal",
      "Ganjam",
      "Gajapati",
      "Jharsuguda",
      "Jajpur",
      "Jagatsinghpur",
      "Khordha",
      "Kendujhar (Keonjhar)",
      "Kalahandi",
      "Kandhamal",
      "Koraput",
      "Kendrapara",
      "Malkangiri",
      "Mayurbhanj",
      "Nabarangpur",
      "Nuapada",
      "Nayagarh",
      "Puri",
      "Rayagada",
      "Sambalpur",
      "Subarnapur (Sonepur)",
      "Sundergarh",
    ],
  },
  {
    title: "Pondicherry",
    values: ["Karaikal", "Mahe", "Pondicherry", "Yanam"],
  },
  {
    title: "Punjab",
    values: [
      "Amritsar",
      "Barnala",
      "Bathinda",
      "Firozpur",
      "Faridkot",
      "Fatehgarh Sahib",
      "Fazilka",
      "Gurdaspur",
      "Hoshiarpur",
      "Jalandhar",
      "Kapurthala",
      "Ludhiana",
      "Mansa",
      "Moga",
      "Sri Muktsar Sahib",
      "Pathankot",
      "Patiala",
      "Rupnagar",
      "Ajitgarh (Mohali)",
      "Sangrur",
      "Nawanshahr",
      "Tarn Taran",
    ],
  },
  {
    title: "Rajasthan",
    values: [
      "Ajmer",
      "Alwar",
      "Bikaner",
      "Barmer",
      "Banswara",
      "Bharatpur",
      "Baran",
      "Bundi",
      "Bhilwara",
      "Churu",
      "Chittorgarh",
      "Dausa",
      "Dholpur",
      "Dungapur",
      "Ganganagar",
      "Hanumangarh",
      "Jhunjhunu",
      "Jalore",
      "Jodhpur",
      "Jaipur",
      "Jaisalmer",
      "Jhalawar",
      "Karauli",
      "Kota",
      "Nagaur",
      "Pali",
      "Pratapgarh",
      "Rajsamand",
      "Sikar",
      "Sawai Madhopur",
      "Sirohi",
      "Tonk",
      "Udaipur",
    ],
  },
  {
    title: "Sikkim",
    values: ["East Sikkim", "North Sikkim", "South Sikkim", "West Sikkim"],
  },
  {
    title: "Tamil Nadu",
    values: [
      "Ariyalur",
      "Chennai",
      "Coimbatore",
      "Cuddalore",
      "Dharmapuri",
      "Dindigul",
      "Erode",
      "Kanchipuram",
      "Kanyakumari",
      "Karur",
      "Madurai",
      "Nagapattinam",
      "Nilgiris",
      "Namakkal",
      "Perambalur",
      "Pudukkottai",
      "Ramanathapuram",
      "Salem",
      "Sivaganga",
      "Tirupur",
      "Tiruchirappalli",
      "Theni",
      "Tirunelveli",
      "Thanjavur",
      "Thoothukudi",
      "Tiruvallur",
      "Tiruvarur",
      "Tiruvannamalai",
      "Vellore",
      "Viluppuram",
      "Virudhunagar",
    ],
  },
  {
    title: "Tripura",
    values: [
      "Dhalai",
      "North Tripura",
      "South Tripura",
      "Khowai",
      "West Tripura",
    ],
  },
  {
    title: "Uttar Pradesh",
    values: [
      "Agra",
      "Allahabad",
      "Aligarh",
      "Ambedkar Nagar",
      "Auraiya",
      "Azamgarh",
      "Barabanki",
      "Budaun",
      "Bagpat",
      "Bahraich",
      "Bijnor",
      "Ballia",
      "Banda",
      "Balrampur",
      "Bareilly",
      "Basti",
      "Bulandshahr",
      "Chandauli",
      "Chhatrapati Shahuji Maharaj Nagar",
      "Chitrakoot",
      "Deoria",
      "Etah",
      "Kanshi Ram Nagar",
      "Etawah",
      "Firozabad",
      "Farrukhabad",
      "Fatehpur",
      "Faizabad",
      "Gautam Buddh Nagar",
      "Gonda",
      "Ghazipur",
      "Gorakhpur",
      "Ghaziabad",
      "Hamirpur",
      "Hardoi",
      "Mahamaya Nagar",
      "Jhansi",
      "Jalaun",
      "Jyotiba Phule Nagar",
      "Jaunpur district",
      "Ramabai Nagar (Kanpur Dehat)",
      "Kannauj",
      "Kanpur",
      "Kaushambi",
      "Kushinagar",
      "Lalitpur",
      "Lakhimpur Kheri",
      "Lucknow",
      "Mau",
      "Meerut",
      "Maharajganj",
      "Mahoba",
      "Mirzapur",
      "Moradabad",
      "Mainpuri",
      "Mathura",
      "Muzaffarnagar",
      "Panchsheel Nagar district (Hapur)",
      "Pilibhit",
      "Shamli",
      "Pratapgarh",
      "Rampur",
      "Raebareli",
      "Saharanpur",
      "Sitapur",
      "Shahjahanpur",
      "Sant Kabir Nagar",
      "Siddharthnagar",
      "Sonbhadra",
      "Sant Ravidas Nagar",
      "Sultanpur",
      "Shravasti",
      "Unnao",
      "Varanasi",
    ],
  },
  {
    title: "Uttarakhand",
    values: [
      "Almora",
      "Bageshwar",
      "Chamoli",
      "Champawat",
      "Dehradun",
      "Haridwar",
      "Nainital",
      "Pauri Garhwal",
      "Pithoragarh",
      "Rudraprayag",
      "Tehri Garhwal",
      "Udham Singh Nagar",
      "Uttarkashi",
    ],
  },
  {
    title: "West Bengal",
    values: [
      "Birbhum",
      "Bankura",
      "Bardhaman",
      "Darjeeling",
      "Dakshin Dinajpur",
      "Hooghly",
      "Howrah",
      "Jalpaiguri",
      "Cooch Behar",
      "Kolkata",
      "Maldah",
      "Paschim Medinipur",
      "Purba Medinipur",
      "Murshidabad",
      "Nadia",
      "North 24 Parganas",
      "South 24 Parganas",
      "Purulia",
      "Uttar Dinajpur",
    ],
  },
];
